"""Diagnose BDM-SNN action readouts on a fully enumerable 2-D task.

All 25 grid locations are explicitly bound to one of four actions during two
teacher sweeps.  This makes the task an upper-bound diagnostic: a failure in
the no-teacher phase cannot be attributed to unobserved states or continuous
robot dynamics.  ``synapse_value`` is a non-SNN reference readout of the
cloned D1/D2 rows, not a deployment result; the other readouts use spikes
generated by the unchanged BDM-SNN forward pass.
"""

import argparse
import json
import random
import sys
from pathlib import Path

import numpy as np
import torch


ROOT = Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from braincog.model_zoo.bdmsnn import BDMSNN


VALUES = (-2, -1, 0, 1, 2)
NUM_STATE = 25
NUM_ACTION = 4


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def state_id(position):
    return VALUES.index(position[0]) + 5 * VALUES.index(position[1])


def teacher_action(position):
    x, y = position
    if abs(x) >= abs(y) and x:
        return 0 if x < 0 else 1
    if y:
        return 2 if y < 0 else 3
    return None


def step(position, action):
    x, y = position
    if action == 0:
        x = min(2, x + 1)
    elif action == 1:
        x = max(-2, x - 1)
    elif action == 2:
        y = min(2, y + 1)
    else:
        y = max(-2, y - 1)
    return x, y


def current(position, device):
    value = torch.zeros(NUM_STATE, dtype=torch.float32, device=device)
    value[state_id(position)] = 2.0
    return value


def clone_update(network, position, action):
    """Install a known state-action preference while retaining BDM-SNN dynamics."""
    with torch.no_grad():
        row = state_id(position)
        action_slice = slice(row * NUM_ACTION, (row + 1) * NUM_ACTION)
        d1 = network.connection[0].weight[row, action_slice]
        d2 = network.connection[1].weight[row, action_slice]
        d1.fill_(0.05)
        d2.fill_(network.weight_exc)
        d1[action] = network.weight_exc
        d2[action] = 0.05


def choose(scores, rng):
    scores = np.asarray(scores, dtype=np.float64)
    winners = np.flatnonzero(np.isclose(scores, scores.max()))
    return int(rng.choice(winners)), int(winners.size)


def decide(network, position, args, device, rng):
    """Run an unchanged SNN decision window and decode one action from it."""
    pm_counts = torch.zeros(NUM_ACTION, dtype=torch.float32, device=device)
    thalamus_counts = torch.zeros(NUM_ACTION, dtype=torch.float32, device=device)
    pm_membrane = torch.zeros(NUM_ACTION, dtype=torch.float32, device=device)
    for _ in range(args.window):
        pm_output, _ = network(current(position, device))
        pm_counts += pm_output.detach()
        thalamus_counts += network.out[5].detach()
        pm_membrane = torch.as_tensor(network.node[6].mem, device=device).detach().clone()

    pm_values = pm_counts.cpu().numpy()
    thalamus_values = thalamus_counts.cpu().numpy()
    membrane_values = pm_membrane.cpu().numpy()
    pm_silent = bool(pm_counts.sum().item() == 0)
    pm_action, pm_tie = choose(pm_values, rng)

    if args.readout == "pm_count":
        action, tie_count = pm_action, pm_tie
    elif args.readout == "pm_count_mem":
        # The PM spike count remains primary; final subthreshold voltage only
        # resolves equal counts and keeps PM as the action-producing region.
        candidates = np.flatnonzero(np.isclose(pm_values, pm_values.max()))
        local = membrane_values[candidates]
        second = candidates[np.flatnonzero(np.isclose(local, local.max()))]
        action = int(rng.choice(second))
        tie_count = int(second.size)
    elif args.readout == "thalamus_count":
        action, tie_count = choose(thalamus_values, rng)
    else:  # A learned-weight upper bound, deliberately not an autonomous PM result.
        row = state_id(position)
        action_slice = slice(row * NUM_ACTION, (row + 1) * NUM_ACTION)
        d1 = network.connection[0].weight[row, action_slice].detach().cpu().numpy()
        d2 = network.connection[1].weight[row, action_slice].detach().cpu().numpy()
        action, tie_count = choose(d1 - d2, rng)
    return {
        "action": action,
        "tie_count": tie_count,
        "pm_action": pm_action,
        "pm_tie_count": pm_tie,
        "pm_silent": pm_silent,
        "pm_counts": pm_values.tolist(),
        "thalamus_counts": thalamus_values.tolist(),
        "pm_membrane": membrane_values.tolist(),
    }


def run(args):
    set_seed(args.seed)
    rng = np.random.default_rng(args.seed)
    device = torch.device(args.device)
    network = BDMSNN(NUM_STATE, NUM_ACTION, 1.0, -0.5, "lif",
                     communication_mode="all_cross_core", pm_threshold=args.pm_threshold,
                     pm_lateral_gain=args.pm_lateral_gain).to(device)
    starts = [(x, y) for x in VALUES for y in VALUES]

    for _ in range(args.teacher_epochs):
        for position in starts:
            network.reset()
            for _ in range(args.max_steps):
                action = teacher_action(position)
                if action is None:
                    break
                # Forward activity and the cloned D1/D2 preference coexist.
                decide(network, position, args, device, rng)
                clone_update(network, position, action)
                position = step(position, action)

    trials = []
    total_decisions = correct_decisions = 0
    total_pm_silent = total_pm_ties = 0
    for start in starts:
        position = start
        network.reset()
        trace = []
        for _ in range(args.max_steps):
            optimal = teacher_action(position)
            if optimal is None:
                break
            detail = decide(network, position, args, device, rng)
            action = detail["action"]
            total_decisions += 1
            correct_decisions += int(action == optimal)
            total_pm_silent += int(detail["pm_silent"])
            total_pm_ties += int(detail["pm_tie_count"] > 1)
            trace.append({"position": position, "optimal": optimal, **detail})
            position = step(position, action)
        trials.append({"start": start, "success": position == (0, 0),
                       "steps": len(trace), "trace": trace})

    result = {
        "task": "enumerate_all_25_discrete_starts",
        "readout": args.readout,
        "window": args.window,
        "pm_threshold": args.pm_threshold,
        "pm_lateral_gain": args.pm_lateral_gain,
        "teacher_epochs": args.teacher_epochs,
        "teacher_decisions": args.teacher_epochs * sum(abs(x) + abs(y) for x, y in starts),
        "deployment_teacher_decisions": 0,
        "success": int(sum(item["success"] for item in trials)),
        "total": len(trials),
        "decision_accuracy": correct_decisions / max(1, total_decisions),
        "pm_silent_rate": total_pm_silent / max(1, total_decisions),
        "pm_tie_rate": total_pm_ties / max(1, total_decisions),
        "trials": trials,
    }
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps({key: value for key, value in result.items() if key != "trials"}, indent=2))


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--readout", choices=("pm_count", "pm_count_mem", "thalamus_count", "synapse_value"),
                        required=True)
    parser.add_argument("--window", type=int, default=12)
    parser.add_argument("--pm-threshold", type=float, default=0.5)
    parser.add_argument("--pm-lateral-gain", type=float, default=-2.5)
    parser.add_argument("--teacher-epochs", type=int, default=2)
    parser.add_argument("--max-steps", type=int, default=8)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--output", required=True)
    return parser.parse_args()


if __name__ == "__main__":
    run(parse_args())
